name: Split Rota Shifts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (adjust as needed)
  push:
    paths:
      - '**/*.py'  # Runs when Python files change

jobs:
  split-shifts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to extract events and create ICS
      run: python split_shifts.py

    - name: Check if ICS files exist
      run: |
        if [ -z "$(ls output/Splits/*.ics 2>/dev/null)" ]; then
          echo "No ICS files generated, skipping commit"
          exit 0
        fi

    - name: Commit ICS files to repo
      run: |
        git config --global user.name "GitHub Actions"
        git config --global user.email "actions@github.com"
        
        # Add all ICS files from the output/Splits folder
        git add output/Splits/*.ics
        
        # Commit the changes
        git commit -m "Update ICS files for BrewDog locations" || echo "No changes to commit"
        
        # Push the changes back to the repository
        git push origin main
