name: Split Rota Shifts

on:
  schedule:
    - cron: '0 0 * * *'  # Runs every day at midnight (adjust as needed)
  push:
    paths:
      - '**/*.py'  # Runs on Python file changes

jobs:
  split-shifts:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run script to extract events and create ICS
      run: python split_shifts.py

    - name: Upload TXT and ICS files as artifacts
      uses: actions/upload-artifact@v3
      with:
        name: event-files
        path: output/Splits/*
